"""Every barcode the PAINT catalog publishes, read live from the committed archive.

LIVE, NOT INDEXED, and that distinction is the whole reason this file is three lines of logic
instead of a generator plus a committed artefact plus a reproducibility test. PR #145 built the
indexed version -- `data/catalog/paint-eans.yaml`, regenerated by the paint workflow and read by
the product resolver -- and it was closed unmerged. The two pipelines run on different cadences
and different branches, so the index is stale exactly when it matters: a paint that gained a
barcode last night keeps the `miniatures` guess tonight, with nothing anywhere saying so.

Reading data/paints/brands/*.yaml costs a walk of ~20 files on a stage that already walks the
whole evidence store, and it cannot be stale by construction.

A BARCODE HERE IS A LABEL AND NOTHING ELSE. Nothing in this package may read it as permission to
drop, refuse or rewrite a product record -- a product and a paint sharing a barcode is the design
(docs/OBJECTIVES.md 4), and the refusal built on exactly this signal (PR #143) was closed unmerged
after it was found to delete 110 published ids.
"""
from pathlib import Path

from warhub_acquisition.yamlio import read_yaml


def load_paint_barcodes(paints_root: Path) -> frozenset[str]:
    """`{barcode}` over every committed paint, primary and additional. Empty if absent.

    STRINGS, ALWAYS. A barcode is a zero-padded numeric string and the lookup is exact string
    membership against a product's published `ean`, so a value that arrived as an int would miss
    silently and the product would keep its guess. The product catalog already holds 1,138
    barcodes of the UPC-A-promoted `0...` shape, which is precisely the population a numeric
    round-trip loses.
    """
    brands = paints_root / "brands"
    if not brands.exists():
        return frozenset()
    codes: set[str] = set()
    for path in sorted(brands.glob("*.yaml")):
        for paint in (read_yaml(path) or {}).get("paints") or []:
            for value in (paint.get("ean"), *(paint.get("additionalEans") or [])):
                if value:
                    codes.add(str(value))
    return frozenset(codes)
