using WarHub.PaintCatalog.Tool.Models;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace WarHub.PaintCatalog.Tool.Enrichment;

/// <summary>
/// Applies the committed manufacturer harvest files (data/paints/harvest/*.yaml, generated by
/// tools/acquisition/scripts/gen_paint_harvest.py) to a brand's paint list.
///
/// Two operations, mirroring the file's two consumed sections (the third, `candidates`, is a
/// report for humans and deliberately ignored here):
///
/// - `additions`: NEW paints proposed by catalog-role sources (manufacturer catalog sites,
///   never storefronts). Appended BEFORE the enrichment chain so VolumeEnricher, the
///   type/finish classifiers, EanComputer and BarcodeEnricher treat them like native paints.
///   Additions carry no colour (manufacturers don't publish hex): Hex is empty and R/G/B zero
///   until an override or a later swatch-extraction pass fills them — empty-hex paints are
///   excluded from equivalence matching (they would otherwise read as pure black).
/// - `enrich`: exact "{Name}|{Set}" identities matched at generation time (fuzzy logic lives
///   in Python, once). Fills ONLY a blank Ean/ImageUrl — same identity discipline as
///   BarcodeEnricher: ProductCode and Hex are part of the identity key and are never touched,
///   even though the harvest file records the store SKU for audit.
/// </summary>
public static class HarvestApplier
{
    private static readonly IDeserializer YamlDeserializer = new DeserializerBuilder()
        .WithNamingConvention(CamelCaseNamingConvention.Instance)
        .IgnoreUnmatchedProperties()
        .Build();

    public sealed class HarvestEntry
    {
        public string? Ean { get; set; }
        public string? ImageUrl { get; set; }
        public string? Sku { get; set; }
        public string? SourceUrl { get; set; }
        public string? Source { get; set; }
    }

    public sealed class HarvestAddition
    {
        public string? Name { get; set; }
        public string? Set { get; set; }
        public string? ProductCode { get; set; }
        public string? Ean { get; set; }
        public string? ImageUrl { get; set; }
        public string? SourceUrl { get; set; }
        public string? Source { get; set; }
    }

    public sealed class BrandHarvest
    {
        public Dictionary<string, HarvestEntry>? Enrich { get; set; }
        public List<HarvestAddition>? Additions { get; set; }
    }

    /// <summary>
    /// Loads every {brand-slug}.yaml in the harvest directory. Missing directory → empty
    /// (the harvest is an optional, separately-generated input, exactly like --barcodes).
    /// </summary>
    public static IReadOnlyDictionary<string, BrandHarvest> Load(string? harvestDir)
    {
        var result = new Dictionary<string, BrandHarvest>(StringComparer.OrdinalIgnoreCase);
        if (string.IsNullOrEmpty(harvestDir) || !Directory.Exists(harvestDir))
            return result;

        foreach (string file in Directory.EnumerateFiles(harvestDir, "*.yaml").OrderBy(f => f))
        {
            Dictionary<string, BrandHarvest>? parsed;
            try
            {
                parsed = YamlDeserializer.Deserialize<Dictionary<string, BrandHarvest>>(
                    File.ReadAllText(file));
            }
            catch
            {
                continue; // a malformed harvest file must never kill the catalog run
            }

            if (parsed is null) continue;
            foreach (var (slug, harvest) in parsed)
            {
                result[slug] = harvest;
            }
        }

        return result;
    }

    /// <summary>
    /// Appends harvested additions for the brand, skipping any whose (Name, Set, ProductCode)
    /// is already present (idempotent when Arcturus catches up with a range we harvested
    /// first). The code MUST be part of the skip key: variant ranges legitimately reuse one
    /// colour name across several codes (True Metallic Metal ships each colour as 4 coded
    /// variants — a name-only key silently dropped 59 of its 79 paints).
    /// </summary>
    public static IReadOnlyList<Paint> AppendAdditions(
        IReadOnlyList<Paint> paints,
        string brandSlug,
        IReadOnlyDictionary<string, BrandHarvest> harvests)
    {
        if (!harvests.TryGetValue(brandSlug, out BrandHarvest? harvest) ||
            harvest.Additions is not { Count: > 0 } additions)
        {
            return paints;
        }

        var existing = new HashSet<string>(
            paints.Select(p => $"{p.Name}|{p.Set}|{p.ProductCode}"), StringComparer.OrdinalIgnoreCase);

        List<Paint> result = paints.ToList();
        foreach (HarvestAddition addition in additions)
        {
            if (string.IsNullOrWhiteSpace(addition.Name) || string.IsNullOrWhiteSpace(addition.Set))
                continue;
            string code = string.IsNullOrWhiteSpace(addition.ProductCode) ? "" : addition.ProductCode!;
            if (!existing.Add($"{addition.Name}|{addition.Set}|{code}"))
                continue;

            result.Add(new Paint
            {
                Name = addition.Name!,
                Set = addition.Set!,
                ProductCode = string.IsNullOrWhiteSpace(addition.ProductCode) ? null : addition.ProductCode,
                R = 0,
                G = 0,
                B = 0,
                Hex = "",
                Ean = string.IsNullOrWhiteSpace(addition.Ean) ? null : addition.Ean,
                ImageUrl = string.IsNullOrWhiteSpace(addition.ImageUrl) ? null : addition.ImageUrl,
            });
        }

        return result;
    }

    /// <summary>
    /// Fills blank Ean/ImageUrl from harvest enrichment entries (exact "{Name}|{Set}" lookup).
    /// Runs before OverrideApplier so a manual override still wins.
    /// </summary>
    public static IReadOnlyList<Paint> ApplyEnrichment(
        IReadOnlyList<Paint> paints,
        string brandSlug,
        IReadOnlyDictionary<string, BrandHarvest> harvests)
    {
        if (!harvests.TryGetValue(brandSlug, out BrandHarvest? harvest) ||
            harvest.Enrich is not { Count: > 0 } enrich)
        {
            return paints;
        }

        // `{Name}|{Set}` is NOT unique -- paint identity is `set|name|productCode|hex`, so a brand
        // can ship two paints differing only by code or colour. Applying a keyed entry to every
        // match therefore copies ONE product's barcode and photo onto BOTH. Measured 2026-08-01:
        // 71 ambiguous keys across 8 brands, 35 of them enriched today, every one putting a single
        // store photo on two genuinely different Vallejo paints (e.g. Bloody Red|Game Air 72.710
        // #CD3230 and 76.010 #D41C1C).
        //
        // The entry's own `sku` resolves it -- all 917 Vallejo enrich entries carry one, and it is
        // the product code of the exact paint the generator matched. So an ambiguous key is
        // disambiguated rather than dropped, and only when the sku picks out exactly one paint.
        // Anything still ambiguous is skipped: guessing which of two paints a photo belongs to is
        // worse than leaving both blank.
        var ambiguous = paints.GroupBy(p => $"{p.Name}|{p.Set}", StringComparer.Ordinal)
            .Where(g => g.Count() > 1)
            .ToDictionary(g => g.Key, g => g.ToList(), StringComparer.Ordinal);

        return paints.Select(p =>
        {
            string key = $"{p.Name}|{p.Set}";
            if (!enrich.TryGetValue(key, out HarvestEntry? entry))
                return p;

            if (ambiguous.TryGetValue(key, out List<Paint>? rivals))
            {
                var owner = rivals
                    .Where(r => !string.IsNullOrWhiteSpace(entry.Sku)
                                && string.Equals(r.ProductCode, entry.Sku, StringComparison.OrdinalIgnoreCase))
                    .ToList();
                if (owner.Count != 1 || !ReferenceEquals(owner[0], p))
                    return p;
            }

            return p with
            {
                Ean = p.Ean ?? (string.IsNullOrWhiteSpace(entry.Ean) ? null : entry.Ean),
                ImageUrl = p.ImageUrl ?? (string.IsNullOrWhiteSpace(entry.ImageUrl) ? null : entry.ImageUrl),
            };
        }).ToList();
    }
}
