using System.Globalization;
using WarHub.PaintCatalog.Tool.Models;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace WarHub.PaintCatalog.Tool.Enrichment;

/// <summary>
/// Applies committed swatch-extraction results (data/paints/swatches/*.yaml, generated by
/// tools/acquisition/scripts/gen_paint_swatches.py from manufacturer chart PDFs) to a brand's
/// paint list.
///
/// Entries are keyed "{Name}|{Set}|{ProductCode}" — the code is REQUIRED in the key because
/// variant ranges (e.g. True Metallic Metal) reuse one colour name across several coded
/// variants whose chart colours differ. Only an EMPTY Hex is ever filled (R/G/B recomputed
/// alongside); existing colours — Arcturus data or manual overrides — always win, and
/// OverrideApplier still runs later so a human override trumps a sampled chart colour too.
/// </summary>
public static class SwatchApplier
{
    private static readonly IDeserializer YamlDeserializer = new DeserializerBuilder()
        .WithNamingConvention(CamelCaseNamingConvention.Instance)
        .IgnoreUnmatchedProperties()
        .Build();

    public sealed class SwatchEntry
    {
        public string? Hex { get; set; }
        public string? Code { get; set; }
        public string? Method { get; set; }
        public string? Chart { get; set; }
        public string? Confidence { get; set; }
    }

    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, SwatchEntry>> Load(
        string? swatchesDir)
    {
        var result = new Dictionary<string, IReadOnlyDictionary<string, SwatchEntry>>(
            StringComparer.OrdinalIgnoreCase);
        if (string.IsNullOrEmpty(swatchesDir) || !Directory.Exists(swatchesDir))
            return result;

        foreach (string file in Directory.EnumerateFiles(swatchesDir, "*.yaml").OrderBy(f => f))
        {
            Dictionary<string, Dictionary<string, SwatchEntry>>? parsed;
            try
            {
                parsed = YamlDeserializer
                    .Deserialize<Dictionary<string, Dictionary<string, SwatchEntry>>>(
                        File.ReadAllText(file));
            }
            catch
            {
                continue; // a malformed swatch file must never kill the catalog run
            }

            if (parsed is null) continue;
            foreach (var (slug, entries) in parsed)
            {
                result[slug] = entries;
            }
        }

        return result;
    }

    public static IReadOnlyList<Paint> Apply(
        IReadOnlyList<Paint> paints,
        string brandSlug,
        IReadOnlyDictionary<string, IReadOnlyDictionary<string, SwatchEntry>> swatches)
    {
        if (!swatches.TryGetValue(brandSlug, out IReadOnlyDictionary<string, SwatchEntry>? entries) ||
            entries.Count == 0)
        {
            return paints;
        }

        return paints.Select(p =>
        {
            if (!string.IsNullOrEmpty(p.Hex))
                return p;
            if (!entries.TryGetValue($"{p.Name}|{p.Set}|{p.ProductCode}", out SwatchEntry? entry))
                return p;
            if (!TryParseHex(entry.Hex, out int r, out int g, out int b))
                return p;

            return p with { Hex = entry.Hex!.ToUpperInvariant(), R = r, G = g, B = b };
        }).ToList();
    }

    internal static bool TryParseHex(string? hex, out int r, out int g, out int b)
    {
        r = g = b = 0;
        if (string.IsNullOrWhiteSpace(hex))
            return false;
        string h = hex.TrimStart('#');
        if (h.Length != 6)
            return false;
        if (!int.TryParse(h[..2], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out r) ||
            !int.TryParse(h[2..4], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out g) ||
            !int.TryParse(h[4..], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out b))
        {
            return false;
        }
        return true;
    }
}
