namespace WarHub.Catalog.Publish;

/// <summary>
/// Canonical, publisher-native DTOs for the migrated catalog layout
/// (<c>data/catalog/products/*.yaml</c> and <c>data/catalog/taxonomy/*.yaml</c>). These are additive:
/// consumed by ProductBuilder via YamlSource.LoadCanonicalCatalogs.
/// </summary>
public sealed record CanonicalProductCatalog
{
    public required string Manufacturer { get; init; }
    public required List<CanonicalProduct> Products { get; init; }
}

public sealed record CanonicalProduct
{
    public required string Id { get; init; }
    public required string Name { get; init; }
    public required string Manufacturer { get; init; }
    public string? ProductCode { get; init; }
    public string? Sku { get; init; }
    public string? Ean { get; init; }
    public string? EanConfidence { get; init; }
    public List<string>? AdditionalEans { get; init; }   // extra barcodes of a repackaged product
    public List<string>? AdditionalCodes { get; init; }  // the maker's other codes for this same box
    public List<string>? Supersedes { get; init; }       // retired product records this one replaces
    public string? SupersededBy { get; init; }           // the current record replacing this retired one
    public string? BundleOf { get; init; }               // the product this web bundle contains
    // Every game this product belongs to, as slugs. A LIST because membership is one: GW's own
    // store shelves 183 products under two systems. `List<string>` and not `IReadOnlyList<string>`
    // deliberately -- YamlDotNet SERIALIZES the interface happily and has no node deserializer for
    // it, so the read side would silently fail.
    public List<string> GameSystems { get; init; } = [];
    // Every SETTING -- universe or period -- this product belongs to, as slugs. Derived from the
    // games by the resolver for most of the catalog; stated directly for the products that belong
    // to a setting and to no game (a novel, a building sold for a whole period). Same `List`
    // reasoning as GameSystems.
    public List<string> Settings { get; init; } = [];
    public string? Faction { get; init; }        // slug
    public string? Category { get; init; }
    // WHAT A HOBBY SUPPLY IS FOR -- categories.yaml axis 3 (colour, primer, varnish, medium,
    // cleaner, texture, pigment, applicator, tool, basing, build). Null for everything that is not
    // a paint or a hobby auxiliary, and for every set. `roleBasis` is deliberately not read: like
    // `categoryBasis` it is archive-side provenance and not part of the published shape.
    public string? Role { get; init; }
    public string? Packaging { get; init; }
    public int? Quantity { get; init; }
    public int? VolumeMl { get; init; }
    /// <summary>Net contents in grams. Sibling of <see cref="VolumeMl"/>; see ProductRecord.</summary>
    public int? WeightG { get; init; }
    public required string Status { get; init; }
    public string? Availability { get; init; }
    public string? FirstSeen { get; init; }
    public decimal? PriceGbp { get; init; }
    public decimal? PriceUsd { get; init; }
    public decimal? PriceEur { get; init; }
    public decimal? PriceCad { get; init; }
    public string? Url { get; init; }
    public string? ImageUrl { get; init; }
    public string? Description { get; init; }
    /// <summary>
    /// The manufacturer's OWN product codes for what a boxed set contains, verbatim from the
    /// source -- not resolved catalog ids. Resolving them needs the paint catalog, which the
    /// Python resolver never loads, so the resolved relation is generated separately into
    /// data/catalog/set-contents/ and is read back by <see cref="SetContents"/>.
    ///
    /// NOT published directly, and that is not an omission: every one of these codes reaches
    /// dist/ through set-contents.json, either as a member's <c>ref</c> (resolved to a paint id)
    /// or as an <c>unresolved</c> entry with the reason it was refused. Measured 2026-08-31, the
    /// two sides are an exact bijection -- 375 products carry this key, the relation holds 375
    /// sets, and 2,225 refs land as 2,214 members + 11 unresolved -- so publishing the raw list
    /// beside the resolved one would restate it, less usefully, in a second place that could
    /// then disagree.
    ///
    /// Declared <c>List</c> rather than <c>IReadOnlyList</c> for the same reason
    /// <see cref="PaintCatalog.Tool.Models.PaintRecord.AdditionalEans"/> is: YamlDotNet
    /// serializes a read-only list happily and has no node deserializer for one, so the round trip
    /// dies the first time a record actually gains the key.
    /// </summary>
    public List<string>? ContentSkus { get; init; }
    public List<string>? Evidence { get; init; }
}

// ---- data/catalog/set-contents/*.yaml -------------------------------------------------------
//
// The boxed-set relation, generated by tools/acquisition/scripts/gen_set_contents.py: every
// `contentSkus` ref joined ONCE, upstream, against the paint archive, so the publisher only ever
// does an exact lookup. One file per MANUFACTURER, each a single top-level key (the manufacturer
// slug) -- hence the outer Dictionary in YamlSource.LoadSetContents rather than a named property.
//
// Every list here is `List<T>`, never `IReadOnlyList<T>`: YamlDotNet has no node deserializer for
// a read-only list, so the round trip dies on the first file that carries the key.

/// <summary>One manufacturer's block: the generator's own tallies plus the sets themselves.</summary>
public sealed record CanonicalSetContentsFile
{
    /// <summary>
    /// The generator's PER-FILE tallies. Read and re-derived rather than trusted: the publisher
    /// counts what it actually publishes, and <see cref="SetContents"/> compares the two so a
    /// stale hand-edit to a generated file cannot pass silently.
    /// </summary>
    public CanonicalSetCounts? Counts { get; init; }

    /// <summary>Keyed by <c>CanonicalProduct.Id</c> -- the published product id, unchanged.</summary>
    public Dictionary<string, CanonicalSet>? Sets { get; init; }
}

public sealed record CanonicalSetCounts
{
    public int Sets { get; init; }
    public int Refs { get; init; }
    public int Members { get; init; }
    public int Unresolved { get; init; }
    public int Quantified { get; init; }
}

public sealed record CanonicalSet
{
    /// <summary>A REVIEW LABEL off the product record. Never join on it.</summary>
    public required string Name { get; init; }

    /// <summary>
    /// The paint archive(s) SEARCHED, comma-joined ("army-painter, ak-interactive"). Not published:
    /// a member's own <c>brand</c> says what was FOUND, and that is the only one safe to join on.
    /// </summary>
    public string? Brand { get; init; }

    /// <summary>Where the refs came from: <c>stated</c> | <c>description</c> | <c>sku</c>.</summary>
    public required string From { get; init; }

    public List<CanonicalSetMember>? Members { get; init; }
    public List<CanonicalSetUnresolved>? Unresolved { get; init; }
}

public sealed record CanonicalSetMember
{
    /// <summary>The source's own code VERBATIM, before normalisation -- the audit link back.</summary>
    public required string Ref { get; init; }

    /// <summary>The archive the paint was FOUND in. Joins with Paint/ProductCode.</summary>
    public required string Brand { get; init; }

    /// <summary><c>{Name}|{Set}</c>. Not unique on its own; ProductCode is the tie-break.</summary>
    public required string Paint { get; init; }

    public string? ProductCode { get; init; }

    /// <summary><c>correction</c> | <c>statedName</c>; absent when the printed code resolved alone.</summary>
    public string? ResolvedBy { get; init; }

    /// <summary>The name printed beside a repeated code, alongside <c>resolvedBy: statedName</c>.</summary>
    public string? StatedName { get; init; }

    /// <summary>How many the source states. ABSENT MEANS THE SOURCE DID NOT SAY, not one unit.</summary>
    public int? Quantity { get; init; }
}

public sealed record CanonicalSetUnresolved
{
    public required string Ref { get; init; }
    public required string Reason { get; init; }
}

public sealed record TaxonomyLabels(
    IReadOnlyDictionary<string, string> GameSystems,
    IReadOnlyDictionary<string, string> Factions,
    IReadOnlyDictionary<string, string> Settings,
    // Which setting each game system belongs to (slug -> slug). Published on the partition
    // index so a consumer can group the game partitions by universe without a second document.
    IReadOnlyDictionary<string, string> SettingOfGameSystem)
{
    public TaxonomyLabels(
        IReadOnlyDictionary<string, string> gameSystems,
        IReadOnlyDictionary<string, string> factions)
        : this(gameSystems, factions, new Dictionary<string, string>(), new Dictionary<string, string>())
    {
    }
}
