# tools/acquisition/tests/test_paint_overrides_gsw_dips.py
"""The hand-written Green Stuff World dipping-ink repair in data/paints/overrides.yaml.

greenstuffworld.com sells 31 dipping-ink colours in a 17 ml and a 60 ml pot -- separate skus,
separate gtin13s, EUR 2.125 vs 3.7375 -- and the paint catalog has ONE record per colour, holding
the 60 ml row's ean, priceEur and imageUrl while `volumeMl: 17` contradicts all three
(`suffix_match` is volume-blind; see its comment in gen_paint_harvest.py). The repair is TWO halves
of one statement, and each half is wrong without the other:

  * `additions: green-stuff-world:` mints the 17 ml pot, whose 31 barcodes were held by nothing;
  * the root `green-stuff-world:` section asserts `volumeMl: 60` on the bare record (it IS the
    60 ml pot) and the minted pots' `priceEur` (a PaintAddition carries no price).

WHAT THESE TESTS ARE FOR. Every value in both halves was GENERATED by joining
data/evidence/products/mfr-greenstuffworld/observations.jsonl on sku, but it lands in a hand-edited
file where the next editor will copy a line and change two digits. Nothing else re-checks it: the
C# fills a blank `Ean` verbatim, `OverrideApplier.Apply` looks its key up in an ORDINAL dictionary
(OverrideApplier.cs:52-55), and a key that matches nothing is a silent no-op -- the same failure
mode `test_every_retract_key_names_exactly_one_committed_paint` exists for. So these re-derive both
halves from the evidence and fail on any drift.

The barcode class is the one with teeth. The repair's whole claim is that it moves ZERO barcodes:
no `ean:` is overridden, so `BarcodeSet.Union` writes no `additionalEans` (OverrideApplier.cs:83),
the 60 ml barcodes stay primary on the same records, and the 17 ml barcodes are new. If a later
edit "corrects" an ean here instead, `report --ean-guard` does NOT catch it -- the union keeps the
displaced barcode as an `additionalEans` entry, `_check_paints` sees a role change and reports
`paint_moved`, exit 0 (report.py:227-240). That regression is silent and green; this is where it
fails instead.

TWO LEGITIMATE STATES, like the retract test. Before the paint tool runs the mints do not exist and
their barcodes are held by nobody; after it they exist as ordinary records holding those barcodes.
Assertions are written to survive both, and to reject the MIXED state -- 30 of 31 present is the
typo signature, not a half-finished run.

Imported by path: the bridge scripts are not part of the installed package (they run standalone
under `uv run --with pyyaml`), same as test_paint_harvest_gsw_names.py.
"""
import importlib.util
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT = REPO_ROOT / "tools/acquisition/scripts/gen_paint_harvest.py"
OBSERVATIONS = REPO_ROOT / "data/evidence/products/mfr-greenstuffworld/observations.jsonl"
BRANDS_DIR = REPO_ROOT / "data/paints/brands"
PRODUCTS_DIR = REPO_ROOT / "data/catalog/products"
HARVEST = REPO_ROOT / "data/paints/harvest/green-stuff-world.yaml"
OVERRIDES = REPO_ROOT / "data/paints/overrides.yaml"

SLUG = "green-stuff-world"
SET = "Dipping Inks"


def _load():
    if not SCRIPT.exists():
        pytest.skip("gen_paint_harvest.py not present (package tested outside the monorepo)")
    spec = importlib.util.spec_from_file_location("gen_paint_harvest_gsw_dips", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _yaml(path):
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _overrides():
    if not OVERRIDES.exists():
        pytest.skip("data/paints/overrides.yaml not present")
    return _yaml(OVERRIDES)


def _mints():
    """The `additions: green-stuff-world:` entries this repair minted -- the Dipping Inks ones.

    Filtered by set rather than taken wholesale so a future GSW mint in another range does not
    silently inherit assertions written about dipping inks.
    """
    additions = ((_overrides().get("additions") or {}).get(SLUG) or [])
    mints = [a for a in additions if (a.get("set") or "") == SET]
    if not mints:
        pytest.skip("no green-stuff-world Dipping Inks additions declared")
    return mints


def _field_overrides():
    section = _overrides().get(SLUG) or {}
    return {k: v for k, v in section.items() if k.endswith(f"|{SET}")}


def _volume_keys():
    return {k: v for k, v in _field_overrides().items() if "volumeMl" in v}


def _price_keys():
    return {k: v for k, v in _field_overrides().items() if "priceEur" in v}


def _observations_by_sku():
    if not OBSERVATIONS.exists():
        pytest.skip("mfr-greenstuffworld evidence not present")
    rows = [json.loads(line) for line in
            OBSERVATIONS.read_text(encoding="utf-8").splitlines() if line.strip()]
    return {str(o.get("sku") or ""): o for o in rows}, {str(o["ean"]): o for o in rows if o.get("ean")}


def _archive():
    path = BRANDS_DIR / f"{SLUG}.yaml"
    if not path.exists():
        pytest.skip("green-stuff-world archive not present")
    return _yaml(path).get("paints") or []


def _holders():
    """barcode -> {(holder, role)} across BOTH catalogs, exactly what `_check_paints` searches."""
    holders = defaultdict(set)
    for path in sorted(BRANDS_DIR.glob("*.yaml")):
        data = _yaml(path)
        brand = str(data.get("brandSlug") or path.stem)
        for record in data.get("paints") or []:
            if record.get("ean"):
                holders[str(record["ean"])].add((brand, "primary"))
            for extra in record.get("additionalEans") or []:
                holders[str(extra)].add((brand, "additional"))
    if PRODUCTS_DIR.exists():
        for path in sorted(PRODUCTS_DIR.glob("*.yaml")):
            for product in _yaml(path).get("products") or []:
                if product.get("ean"):
                    holders[str(product["ean"])].add((f"products/{path.stem}", "product"))
                for extra in product.get("additionalEans") or []:
                    holders[str(extra)].add((f"products/{path.stem}", "product"))
    return holders


class TestEveryMintedPotIsARealStoreProduct:
    """Each addition must be the 17 ml sku it claims to be, joined not transcribed."""

    def test_every_mint_carries_its_own_evidence_rows_ean_and_image(self):
        by_sku, _ = _observations_by_sku()
        wrong = []
        for mint in _mints():
            row = by_sku.get(str(mint.get("productCode") or ""))
            if row is None:
                wrong.append((mint["name"], mint.get("productCode"), "no observation with that sku"))
                continue
            if str(mint.get("ean") or "") != str(row.get("ean") or ""):
                wrong.append((mint["name"], mint.get("ean"), f"sku {row['sku']} has {row.get('ean')}"))
            if mint.get("imageUrl") != row.get("imageUrl"):
                wrong.append((mint["name"], "imageUrl", row.get("imageUrl")))
        assert not wrong, (
            "minted pots whose fields disagree with the observations row named by their "
            f"productCode: {wrong}"
        )

    def test_every_mint_is_the_seventeen_ml_pot(self):
        """`hints.ml` is the store title's own volume (sitemap_sd_paints.py parses it there).

        This is the assertion the whole repair rests on: the record beside these already holds
        the 60 ml barcode, so a mint pointing at a second 60 ml sku would publish the same pot
        twice under two names.
        """
        by_sku, _ = _observations_by_sku()
        assert Counter(
            (by_sku[str(m["productCode"])].get("hints") or {}).get("ml") for m in _mints()
        ) == {17: len(_mints())}

    def test_every_minted_barcode_passes_the_check_digit(self):
        module = _load()
        bad = [(m["name"], m.get("ean")) for m in _mints() if not module.ean13_ok(m.get("ean"))]
        assert not bad, f"minted barcodes failing the EAN-13 check digit: {bad}"

    def test_every_mint_spells_its_name_the_way_the_generator_would(self):
        """`gsw_clean_name` spelling, so a future bridge change DEDUPS instead of duplicating.

        `OverrideApplier.AppendAdditions` keys idempotency on {Name}|{Set}|{ProductCode}
        (OverrideApplier.cs:132-141) and `HarvestApplier` runs first (PaintCatalogApp.cs:210). The
        day `bridge_gsw` promotes these contested rows to `additions`, one character of drift here
        -- "17ml" for "17 ml" -- turns these 31 hand entries into 31 duplicate records instead of
        31 no-ops.
        """
        module = _load()
        by_sku, _ = _observations_by_sku()
        wrong = [(m["name"], module.gsw_clean_name(by_sku[str(m["productCode"])]["name"]))
                 for m in _mints()
                 if m["name"] != module.gsw_clean_name(by_sku[str(m["productCode"])]["name"])]
        assert not wrong, f"minted names the generator would spell differently: {wrong}"

    def test_no_mint_duplicates_an_identity_that_already_exists(self):
        """The triple must be new to BOTH appenders, or the mint is a second record for one pot.

        Skipped once the tool has run: the mint is then in the archive under its own triple, which
        is `AppendAdditions` being idempotent, not a collision. All-or-nothing, so a mix still
        fails.
        """
        triples = [f"{m['name']}|{SET}|{m.get('productCode') or ''}".casefold() for m in _mints()]
        assert len(set(triples)) == len(triples), "two mints share one identity triple"

        archived = {f"{r['name']}|{(r.get('details') or {}).get('set') or ''}|"
                    f"{r.get('productCode') or ''}".casefold() for r in _archive()}
        present = [t for t in triples if t in archived]
        assert len(present) in (0, len(triples)), (
            f"{len(present)} of {len(triples)} minted triples are in the archive and the rest are "
            "not -- before the paint tool none should be, after it all should. A mix means one "
            f"mint was retyped and now mints a SECOND record: {sorted(present)[:5]}"
        )

        harvested = {f"{a['name']}|{a.get('set') or ''}|{a.get('productCode') or ''}".casefold()
                     for a in ((_yaml(HARVEST).get(SLUG) or {}).get("additions") or [])} \
            if HARVEST.exists() else set()
        clash = sorted(set(triples) & harvested)
        assert not clash, (
            "the generated harvest already mints these triples -- the hand entries are now "
            f"redundant and should be deleted rather than left to race it: {clash}"
        )


class TestTheBareRecordIsTheSixtyMlPot:
    """The other half: the `volumeMl: 60` assertions, and the prices the mints cannot carry."""

    def test_every_volume_assertion_names_exactly_one_committed_record(self):
        """`Apply` looks the key up ORDINALLY (OverrideApplier.cs:52-55) -- a miss is silent.

        Unlike the mint keys, these name Arcturus-origin records that exist in every state of the
        pipeline, so "exactly one" holds before and after the tool runs.
        """
        counts = Counter(f"{r['name']}|{(r.get('details') or {}).get('set') or ''}"
                         for r in _archive())
        missing = [k for k in _volume_keys() if counts[k] != 1]
        assert not missing, (
            f"volume-assertion keys naming {[counts[k] for k in missing]} records instead of one "
            f"-- OverrideApplier would silently skip them: {missing}"
        )

    def test_every_asserted_volume_is_the_one_that_barcode_belongs_to(self):
        """The premise, re-derived: ean, priceEur and imageUrl all describe the 60 ml sku.

        If any of the three stops agreeing with the observation, the record is no longer plausibly
        "the 60 ml pot" and asserting 60 becomes a fabrication -- which is exactly the state the
        repair claims to have removed, arrived at from the other direction.
        """
        _, by_ean = _observations_by_sku()
        by_key = {f"{r['name']}|{(r.get('details') or {}).get('set') or ''}": r for r in _archive()}
        wrong = []
        for key, override in _volume_keys().items():
            record = by_key.get(key)
            if record is None:
                continue  # reported by the test above
            row = by_ean.get(str(record.get("ean") or ""))
            if row is None:
                wrong.append((key, "ean joins no observation", record.get("ean")))
                continue
            hinted = (row.get("hints") or {}).get("ml")
            if hinted != override["volumeMl"]:
                wrong.append((key, f"asserted {override['volumeMl']} ml", f"barcode is {hinted} ml"))
            if record.get("priceEur") != row.get("priceEur"):
                wrong.append((key, "priceEur", f"{record.get('priceEur')} vs {row.get('priceEur')}"))
            if record.get("imageUrl") != row.get("imageUrl"):
                wrong.append((key, "imageUrl", row.get("imageUrl")))
        assert not wrong, f"volume assertions the evidence does not support: {wrong}"

    def test_every_minted_pot_has_the_price_its_addition_cannot_carry(self):
        """`PaintAddition` has no price field (OverrideApplier.cs:291-302).

        Without the companion entry a minted pot publishes with no price at all -- and the
        harvest cannot supply one either, since these rows sit in `candidates`.
        """
        by_sku, _ = _observations_by_sku()
        prices = _price_keys()
        wrong = []
        for mint in _mints():
            key = f"{mint['name']}|{SET}"
            if key not in prices:
                wrong.append((key, "no priceEur override"))
                continue
            quoted = by_sku[str(mint["productCode"])].get("priceEur")
            if prices[key]["priceEur"] != quoted:
                wrong.append((key, prices[key]["priceEur"], f"store quotes {quoted}"))
        assert not wrong, f"minted pots whose asserted price is missing or not the store's: {wrong}"

    def test_the_two_halves_describe_the_same_colours(self):
        """One statement, two sections: every 60 ml assertion has a 17 ml pot, and vice versa.

        Half a repair is worse than none -- a bare record asserted at 60 ml with no 17 ml pot
        anywhere deletes the 17 ml pot from the catalog's account of the range.

        "Anywhere" is the point, and an earlier draft got it wrong by requiring the 17 ml pot to
        be MINTED HERE. Two of the 33 already have one as a committed archive record --
        `Green Stone Dip 17 ml` (4220) and `Nightshade Purple Dip 17 ml` (4231), which exist
        because their 60 ml titles suffix-matched a different catalog key. Their 60 ml halves
        still needed the volume assertion (one of them is literally NAMED `60 ml` while
        publishing 17), so requiring a mint would have forced either a duplicate record or
        leaving two records at the wrong volume beside 31 corrected ones.
        """
        # The one pair the names cannot join by themselves. greenstuffworld.com misspells the
        # 60 ml listing "NIGHTSAHDE" and spells the 17 ml one correctly, and BOTH spellings are
        # archived verbatim -- that typo is exactly why `suffix_match` saw one claimant here
        # instead of two, so it is the cause of this record's exception, not a nuisance beside it.
        # Named rather than papered over with fuzzy matching: a test that tolerates a one-letter
        # difference would also pair two genuinely different colours.
        SPELLING = {"Nightsahde Purple Dip": "Nightshade Purple Dip"}

        minted = {m["name"] for m in _mints()}
        archived = {p["name"] for p in _archive()
                    if (p.get("details") or {}).get("set") == SET}
        unpaired = []
        for key in _volume_keys():
            bare = key.rsplit("|", 1)[0]
            # A key already carrying the volume names its own pot; strip it before pairing.
            colour = bare[: -len(" 60 ml")] if bare.endswith(" 60 ml") else bare
            colour = SPELLING.get(colour, colour)
            if f"{colour} 17 ml" not in minted | archived:
                unpaired.append(bare)
        assert not unpaired, (
            f"60 ml assertions whose 17 ml pot is neither minted here nor already in the "
            f"archive: {sorted(unpaired)}"
        )

        # ...and the converse: nothing is minted whose 60 ml half goes unasserted.
        asserted = {k.rsplit("|", 1)[0] for k in _volume_keys()}
        orphan_mints = [
            m["name"] for m in _mints()
            if m["name"][: -len(" 17 ml")] not in asserted
            and m["name"].replace(" 17 ml", " 60 ml") not in asserted
        ]
        assert not orphan_mints, (
            f"minted 17 ml pots whose 60 ml half carries no volume assertion: "
            f"{sorted(orphan_mints)}"
        )
        assert {f"{m['name']}|{SET}" for m in _mints()} == set(_price_keys())


class TestTheRepairMovesNoBarcode:
    """The claim `report --ean-guard` cannot check, because the guard would pass either way."""

    def test_no_dipping_ink_override_touches_a_barcode(self):
        """An `ean:` here does not REPLACE a barcode, it demotes one.

        `Apply` unions the displaced value into `additionalEans` (OverrideApplier.cs:83) and
        `Merge` does it again (PaintRecordAdapter.cs:31), so correcting an ean would publish a
        60 ml pot's gtin13 as an alternate barcode of a 17 ml pot -- the "factual lie"
        report.py:200-203 names -- while `_check_paints` reports only `paint_moved` and exits 0.
        """
        offenders = {k: sorted(v) for k, v in _field_overrides().items()
                     if "ean" in v or "additionalEans" in v}
        assert not offenders, (
            "dipping-ink overrides asserting a barcode. The repair mints the pot that owns the "
            f"other barcode instead, precisely so nothing is displaced: {offenders}"
        )

    def test_every_sixty_ml_barcode_is_still_its_own_records_primary(self):
        holders = _holders()
        by_key = {f"{r['name']}|{(r.get('details') or {}).get('set') or ''}": r for r in _archive()}
        wrong = []
        for key in _volume_keys():
            record = by_key.get(key)
            if record is None or not record.get("ean"):
                continue
            if (SLUG, "primary") not in holders[str(record["ean"])]:
                wrong.append((key, record["ean"], sorted(holders[str(record["ean"])])))
        assert not wrong, f"60 ml barcodes that left (green-stuff-world, primary): {wrong}"

    def test_every_minted_barcode_is_held_by_nothing_or_by_its_own_mint(self):
        """The 31 barcodes this repair claims were unhomed, checked in both catalogs.

        Before the tool runs every one is held by nobody (that absence is the whole reason to
        mint); after it every one is the primary `ean` of the minted record. A MIX means a hand
        entry copied a barcode some other record already carries -- publishing one pot's gtin13
        on two paints, which no guard reports.
        """
        holders = _holders()
        held, free = [], []
        for mint in _mints():
            owners = holders.get(str(mint.get("ean") or "")) or set()
            if not owners:
                free.append(mint["name"])
            elif owners == {(SLUG, "primary")}:
                held.append(mint["name"])
            else:
                pytest.fail(
                    f"minted barcode {mint['ean']} ({mint['name']}) is held by {sorted(owners)} "
                    "-- it belongs to another record already"
                )
        assert not (held and free), (
            f"{len(held)} minted barcodes are in the catalog and {len(free)} are not. Before the "
            "paint tool none should be, after it all should; a mix means one of them was retyped "
            f"into an existing record's barcode. Suspect: {sorted(free)[:5]}"
        )
