"""Generate data/catalog/paint-eans.yaml -- every barcode the PAINT catalog already publishes.

WHY THIS FILE EXISTS. Every product record needs a `category`, and when no source said anything
`resolve/attributes.py` wrote `miniatures` unconditionally. That is a GUESS wearing an assertion's
clothes (docs/OBJECTIVES.md 5), and for a paint it is simply false. Measured 2026-08-21 on
catalog/acquisition: 1,072 individual pots published as `category: miniatures` -- vallejo 570,
army-painter 490, green-stuff-world 12 -- against 948 that said `paint` only because their source
stated it (games-workshop 838 off mfr-gw-trade's `Range` column, steamforged-games 110 off
mfr-warmachine's product_type map). The retailers that supply the other 1,072 (ret-goblingaming,
mfr-warlord-store, ret-tistaminis, ret-radaddel) emit no category signal at all: their evidence
carries `hints: {}` on every row.

THIS INDEX LABELS. IT MUST NEVER REFUSE. A pot is legitimately a product AND a paint -- that
overlap is the design, not duplication (OBJECTIVES 4, and
tools/WarHub.Catalog.Publish/CrossCatalogLinks.cs, which reconciles the two sides on exactly the
barcode key this file is built from). PR #143 built a refusal on this same index; it would have
deleted 110 live ids and was closed unmerged. Nothing here may remove a record, and the resolver
consults it in ONE place: where the category would otherwise have been the guess. A source that
states a category still wins, and so does an override.

WHY A COMMITTED INDEX RATHER THAN READING data/paints/ FROM THE RESOLVER. The product resolver
deliberately never loads the paint catalog (models/catalog.py::contentSkus), which is why the
boxed-set relation is generated separately into data/catalog/set-contents/ instead of joined
inline. This keeps that boundary: the cross-catalog question is answered ONCE, here, and the
committed YAML is the audit trail -- same architecture as gen_paint_barcodes.py and
gen_set_contents.py, and the same posture: reads only committed files, no network, deterministic,
byte-identical on re-run. The resolver then does an exact set-membership test, never a fuzzy join.

WHY NOT THE PAINT SOURCES' OWN EVIDENCE, which the resolver already has in memory and which would
need no committed file at all. Because it does not cover the catalog. Measured 2026-08-21: the
committed paint archives publish 3,965 barcodes, while the ten `catalog: paints` sources' live
observations carry 1,485 -- and the 2,829 the sources do not carry include ALL 1,487 vallejo
barcodes (the largest mislabelled population by far), all 838 citadel-colour, 394 mr-hobby and 110
p3. The paint archive is append-only and keeps what a one-off snapshot harvest no longer re-states;
the live sweep is not a substitute for it, and OBJECTIVES 1 says so in general terms.

`additionalEans` ARE INCLUDED, and the difference is not cosmetic: 535 of the 3,965 barcodes come
from there. Omitting them would leave every repackaged paint's older barcode to fall back to the
guess -- precisely the records the archival-identity work exists to keep addressable (OBJECTIVES
3), so mislabelling them is the worst of both.

WHAT THIS FILE IS NOT. It is not a claim that a barcode may appear in only one catalog, and it is
not a duplicate check. It answers exactly one question: does the paint catalog publish this
barcode?

Runnable directly: `uv run --with pyyaml python tools/acquisition/scripts/gen_paint_eans.py`
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[3]
BRANDS_DIR = REPO / "data/paints/brands"
OUT_PATH = REPO / "data/catalog/paint-eans.yaml"

# Same pure-pyyaml sys.path bootstrap gen_paint_harvest.py documents at length: this script runs as
# `uv run --with pyyaml python ...` in CI, and yamlio imports only stdlib + yaml.
sys.path.insert(0, str(REPO / "tools/acquisition/src"))
from warhub_acquisition.yamlio import dump_yaml  # noqa: E402

HEADER = (
    "# GENERATED by tools/acquisition/scripts/gen_paint_eans.py -- do not hand-edit.\n"
    "# Every barcode the paint catalog publishes, primary and additional, against the paint that\n"
    "# carries it. resolve/attributes.py labels a product `category: paint` when its barcode is\n"
    "# here AND no source stated a category -- it never refuses, drops or rewrites a record.\n"
    "# Regenerate after any data/paints/brands change.\n"
)


def build_index(brands_dir: Path) -> dict:
    """`{ean: "<brand>|<name>|<set>"}` over every committed brand archive.

    The value is an AUDIT LABEL, never read by the resolver -- which only asks whether the key is
    present. It is here so a maintainer reading a `category: paint` product can see in one grep
    which paint decided it, the same reason gen_paint_barcodes.py emits its match evidence.

    A barcode carried by more than one paint keeps the FIRST in sorted-brand, file order and is not
    an error here: presence is the whole question this file answers, and within-brand double-holds
    are already policed by tests/test_repo_data.py's barcode guard. Recording one holder keeps the
    file a plain map and the diff readable.
    """
    eans: dict[str, str] = {}
    from_additional = 0
    paints = 0
    brands = 0
    for path in sorted(brands_dir.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        rows = doc.get("paints") or []
        if not rows:
            continue
        brands += 1
        slug = doc.get("brandSlug") or path.stem
        for paint in rows:
            paints += 1
            label = f"{slug}|{paint.get('name', '')}|{(paint.get('details') or {}).get('set') or ''}"
            primary = paint.get("ean")
            for value in [primary, *(paint.get("additionalEans") or [])]:
                if not value:
                    continue
                code = str(value)
                if code in eans:
                    continue
                eans[code] = label
                if value is not primary:
                    from_additional += 1
    return {
        "schemaVersion": 1,
        "counts": {
            "brands": brands,
            "paints": paints,
            "eans": len(eans),
            "fromAdditionalEans": from_additional,
        },
        "eans": {ean: eans[ean] for ean in sorted(eans)},
    }


def main() -> int:
    if not BRANDS_DIR.exists():
        print(f"no brands dir at {BRANDS_DIR}", file=sys.stderr)
        return 1
    index = build_index(BRANDS_DIR)
    # write_bytes (not write_text) so the committed file is LF on every platform, and dump_yaml
    # (not yaml.safe_dump) because a barcode is a zero-padded numeric STRING: safe_dump emits
    # `0812152031524: ...` unquoted and a YAML 1.2 consumer reads that key as a number, which
    # would silently miss every UPC-A-promoted barcode on lookup. The product catalog already
    # holds 1,138 of that shape; the paint side holds none TODAY, which is exactly the kind of
    # fact that changes without anyone revisiting this line. yamlio force-quotes the shape.
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_bytes((HEADER + dump_yaml(index)).encode("utf-8"))
    counts = index["counts"]
    print(f"wrote {OUT_PATH.relative_to(REPO)}: {counts['eans']} barcodes "
          f"({counts['fromAdditionalEans']} from additionalEans) "
          f"from {counts['paints']} paints across {counts['brands']} brands")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
