"""Generate data/catalog/paint-eans.yaml — every barcode the PAINT catalog already publishes.

WHY THIS FILE EXISTS. Retailer (and distributor) sources sell paints, and nothing stopped the
product resolver minting a second, duplicate record for one. Measured 2026-08-20 on
catalog/acquisition: 1,058 individual paints published as `category: miniatures` products —
vallejo 570, army-painter 476, green-stuff-world 12 — every one of them a single retail unit
whose barcode the paint catalog already carries. PR #75 fixed the same defect one level up, for
paint SOURCES (`SourceDescriptor.catalog`), but that field is per-source and cannot help a
retailer that legitimately sells both paints and miniatures.

WHY A COMMITTED INDEX RATHER THAN READING data/paints/ FROM THE RESOLVER. The product resolver
deliberately never loads the paint catalog (models/catalog.py:59-62), which is why the boxed-set
relation is generated separately into data/catalog/set-contents/ instead of joined inline. This
keeps that boundary: the cross-catalog question is answered ONCE, here, and the committed YAML is
the audit trail — same architecture as gen_paint_barcodes.py and gen_set_contents.py, and the
same posture: reads only committed files, no network, deterministic, byte-identical on re-run.
The resolver then does an exact set-membership test, never a fuzzy join.

`additionalEans` ARE INCLUDED, and the difference is not cosmetic. 273 paints carry one; the
index is 3,965 barcodes with them and 3,430 without. Omitting them would leave every repackaged
paint's older barcode free to publish as a product — precisely the records the archival-identity
work exists to keep addressable, so letting them back in under a second identity is the worst of
both.

WHAT THIS FILE IS NOT. It is not an assertion that a barcode may never appear in the product
catalog. A trade CASE PACK legitimately shares a barcode with the pot it contains — see
`SourceDescriptor.tradeUnits` and resolve/resolver.py, which is where that exemption lives. This
file only answers "does the paint catalog publish this barcode?".
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
BRANDS_DIR = REPO_ROOT / "data" / "paints" / "brands"
OUT_PATH = REPO_ROOT / "data" / "catalog" / "paint-eans.yaml"

HEADER = (
    "# GENERATED by tools/acquisition/scripts/gen_paint_eans.py -- do not hand-edit.\n"
    "# Every barcode the paint catalog publishes, primary and additional, keyed to the paint\n"
    "# that carries it. The product resolver refuses to publish a product on one of these\n"
    "# unless a `tradeUnits` source corroborates it. Regenerate after any data/paints change.\n"
)


def build_index(brands_dir: Path) -> dict:
    """{ean: "<brand>|<name>|<set>"} over every committed brand file.

    A barcode carried by more than one paint keeps the FIRST in sorted-brand, file order and is
    not an error here: the refusal only needs to know the barcode belongs to the paint catalog,
    and within-brand double-holds are already policed by
    tests/test_repo_data.py's barcode guard. Recording one owner keeps the file a plain map and
    the diff readable; the guard that cares about duplicates is not this one.
    """
    eans: dict[str, str] = {}
    paints = 0
    brands = 0
    for path in sorted(brands_dir.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        rows = doc.get("paints") or []
        if not rows:
            continue
        brands += 1
        slug = doc.get("brandSlug") or path.stem
        for paint in rows:
            paints += 1
            label = f"{slug}|{paint.get('name', '')}|{(paint.get('details') or {}).get('set') or ''}"
            for value in [paint.get("ean"), *(paint.get("additionalEans") or [])]:
                if value:
                    eans.setdefault(str(value), label)
    return {
        "schemaVersion": 1,
        "counts": {"brands": brands, "paints": paints, "eans": len(eans)},
        "eans": {ean: eans[ean] for ean in sorted(eans)},
    }


def main() -> int:
    if not BRANDS_DIR.exists():
        print(f"no brands dir at {BRANDS_DIR}", file=sys.stderr)
        return 1
    index = build_index(BRANDS_DIR)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(index, sort_keys=False, allow_unicode=True, default_flow_style=False)
    OUT_PATH.write_text(HEADER + body, encoding="utf-8", newline="\n")
    counts = index["counts"]
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}: {counts['eans']} barcodes "
          f"from {counts['paints']} paints across {counts['brands']} brands")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
